### ISSUE TITLE
Plugins / Modules / Store not working

### ISSUE THREAD

**Issue by Simolation** [Exeteres/electron-nuxt-ts#9]
I was so happy to find this template as it allows me to use nuxt directly inside of electron, but for now I can't get plugins, custom modules and the vuex store working. As soon as I add one I get this error:
`This dependency was not found:   * ..\..\src\renderer\store\index.ts in ./dist/.nuxt/store.js`

For plugins and modules I get this error: 
`This dependency was not found: * nuxt_plugin_mymodule_3032cf79 in ./dist/.nuxt/index.js`

I can't get it to work. Do you have any idea what the problem could be and how to solve it?

**Comment by Exeteres** [comment]
Can you provide an example of code that doesn't work?

Just got a working plugin:
![изображение](https://user-images.githubusercontent.com/29506045/100540711-80e33800-3271-11eb-9d3c-31f220e7a369.png)
![изображение](https://user-images.githubusercontent.com/29506045/100540715-8a6ca000-3271-11eb-8fdf-182ef6f18710.png)

Console output in dev mode:
![изображение](https://user-images.githubusercontent.com/29506045/100540718-90628100-3271-11eb-96ee-eb3921861a09.png)
And after build:
![изображение](https://user-images.githubusercontent.com/29506045/100540780-1bdc1200-3272-11eb-82ee-c014b72932c1.png)

Also tested vanila vuex store like in this [guide](https://typescript.nuxtjs.org/cookbook/store.html#vanilla).

Everything seems to work as expected.

**Comment by Simolation** [comment]
I just figured out why it wasn't working: When you bump the typescript version up to 4.1.2 it doesn't work anymore. This is also the case with your example. I will just leave it at 3.8.3 then. 

Thanks for you response :)
